update pipeline

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,5 +1,5 @@
 pipeline {
-    agent any
+    agent { label 'worker' }
 
     environment {
         IMAGE_NAME = "test-pipeline"
@@ -17,36 +17,30 @@ pipeline {
 
         stage('Build Docker Image') {
             steps {
-                script {
-                    sh "docker build -t $IMAGE_NAME ."
-                }
+                sh "docker build -t ${IMAGE_NAME} ."
             }
         }
 
         stage('Stop Old Container') {
             steps {
-                script {
-                    sh "docker rm -f $CONTAINER_NAME || true"
-                }
+                sh "docker rm -f ${CONTAINER_NAME} || true"
             }
         }
 
         stage('Run Container') {
             steps {
-                script {
-                    sh "docker run -d -p $PORT:5000 --name $CONTAINER_NAME $IMAGE_NAME"
-                }
+                sh "docker run -d -p ${PORT}:5000 --name ${CONTAINER_NAME} ${IMAGE_NAME}"
             }
         }
     }
 
     post {
         success {
-            echo "Pipeline Success - App Deployed!"
+            echo "✅ Pipeline Success - App Deployed!"
         }
 
         failure {
-            echo "Pipeline Failed"
+            echo "❌ Pipeline Failed"
         }
     }
 }
